[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "24"
 VITE_SUPABASE_URL=https://gjkmhewssjcccadksvsu.supabase.co
VITE_SUPABASE_ANON_KEY=sb_publishable_52zvS9gEqdJzlfjQzAaF3A_X7q-UO8-

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
